### PR TITLE
Make CLI explict and add unit tests

### PR DESCRIPTION
**Pull request by heckj**
- What had been `noise-tests` is now `generate-noise`, with code moved to its own directory under Sources, and output generated in the `examples` directory at the root of the project. A bit has been added to the README to explain how to invoke it and regenerate the noise.
- NoiseTests continues to exist, but now as an explicit swift testTarget (that is, unit test), with a stub placeholder test. I saw there were array out of bounds issues reported for the project, so I thought to capture those in a unit test and resolve them.

### CODE REVIEW

**Comment by tayloraswift** [comment]
two unrelated comments:

1. what are your thoughts on adopting the new [swift-testing](https://github.com/apple/swift-testing) framework?
2. i’m not seeing any changes to the `Noise` module. was #11 user error?

**Comment by heckj** [comment]
No qualms about reaching for swift-testing, it looks like a nice setup, but I was under the impression it wasn't really ready for use until Swift 6 hits the streets, so I've been waiting myself. Hopefully next week will show us the path they're aiming for there.

I haven't made any changes to Noise - this PR was all just setup to allow me to do so. When I looked through the open issues, both #11 and #3 appear to be reporting the same problem, and when i followed the details on #11, the author had worked around the issue in his own code, but other than seeing that he'd done something with his own fork, I didn't explore deeply. So I don't think it's user-error, and likely is a bug - I was going to put the content from #11 into an issue, and then dig on it, seeing what he did to work around it, to propose a fix. This was a "keep it working exactly as is, just reconfigure things a bit" PR to prep for that.

**Comment by tayloraswift** [comment]
there is a little bit of friction when using swift-testing [with 5.10](https://swiftinit.org/docs/swift-testing/testing/temporarygettingstarted#Swift%205.10) but i am already using it in [swift-json](https://github.com/tayloraswift/swift-json/blob/master/Package.swift) and the toolchain requirement doesn’t seem to be a hard requirement. 

writing the tests against swift-testing means we won’t have to rewrite all the tests against a different framework in a few months time, which i imagine would involve much more effort than dealing with whatever breakages happen between swift-testing 0.9 and 1.0. plus, we can help out @grynspan and give him feedback from using the library in a popular, real-world project. WDYT?

**Comment by heckj** [comment]
Works for me - I'm game. I'm doing all my development in Xcode, which may present more of a challenge, but lets give it a shot. Worst case, I'll run all the tests from the CLI

**Comment by tayloraswift** [comment]
it just occurred to me that we should put the `swift-testing`-dependent tests in a sub-package, similar to the benchmarks, so we don’t conflict with anyone’s macros.

**Comment by heckj** [comment]
I understand your concern re: putting swift-testing in a subproject, but to me that drops the value of doing it all quite a lot. My goal was to have a fast path for "swift test" to replicate an issue, after which fixes could be quickly verified.  I'm working from Xcode, so the test/build is pretty tightly linked, and working across projects With Xcode is a huge limitation - you basically can't have both open and functional at once, due to quirks of how they're handling dependencies.

**Comment by tayloraswift** [comment]
yeah that’s a fair point. the lesson (which i only painfully learned yesterday) is that swift-testing is *poisonous* to a build tree, if it goes in the `Package.swift`, it effectively prevents anyone from touching macros (directly or indirectly) and using swift-noise at the same time.

from asking around yesterday i don’t get the impression from their side that there is much desire to address the problem with 5.10, and they don’t seem to have much of a [recommendation](https://github.com/apple/swift-testing/pull/338) beyond “don’t use SwiftSyntax”. so i think the only conclusion we can reach is that swift-testing in its current state simply cannot co-exist with macros (and must be removed from swift-json as well).

in light of that i’m fine with forgetting about swift-testing entirely and if that’s your position too we can just merge this PR as-is.

**Pull request merged**
